version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/cli
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: "386"
      - goos: linux
        goarch: "386"

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macos{{- else if eq .Os "windows" }}windows{{- else if eq .Os "linux" }}linux{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

release:
  draft: true
  replace_existing_draft: true
  name_template: "v{{.Version}}"
