# Credit: https://github.com/5rahim/seanime/blob/main/.github/ISSUE_TEMPLATE/feature_request.yml

name: Feature request
description: Suggest an idea for the project
labels:
  - feature-request

body:
  - type: checkboxes
    id: '1'
    attributes:
      label: Checklist
      description: >-
        Please check the following before submitting a feature request. If you
        are unable to check all the boxes, please provide more information in the
        description.
      options:
        - label: >-
            I checked that this feature has not been requested before
          required: true
        - label: >-
            I checked that this feature is not in the "Not planned" list
          required: true

  - type: textarea
    id: '2'
    attributes:
      label: Problem Description / Use Case
      description: Provide a detailed description of the problem you are facing or the use case you have in mind.
    validations:
      required: true
  
  - type: textarea
    id: '3'
    attributes:
      label: Proposed Solution
      description: Provide a detailed description of the solution you'd like to see. If you have any ideas on how to implement the feature, please include them here.
    validations:
      required: true
