name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: |
          go mod download
      - name: Test with the Go CLI
        run: go test ./internal/connectors/...
        env:
          IGNORE_TESTS: comic-walker.com